# Generated by Django 4.1.4 on 2022-12-19 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_invoice',
            name='created',
            field=models.DateTimeField(default=None, verbose_name=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user_invoice',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
