# Generated by Django 4.1.4 on 2022-12-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_invoice_created_user_invoice_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_invoice',
            name='created',
        ),
    ]
