# Generated by Django 4.1.4 on 2022-12-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_invoice_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_invoice',
            name='delivered',
        ),
    ]
