# Generated by Django 4.1.4 on 2022-12-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_invoice',
        ),
    ]
