# Generated by Django 4.1.4 on 2022-12-19 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_user_invoice_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_invoice',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
