# Generated by Django 4.1.4 on 2022-12-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_user_invoice_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_invoice',
            name='itemid',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
