# Generated by Django 4.1.4 on 2022-12-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Giftcards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=50)),
                ('redeemed', models.BooleanField(default=False)),
                ('to', models.CharField(max_length=50)),
            ],
        ),
    ]
