# Generated by Django 4.1.4 on 2022-12-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0002_giftcardtype_giftcards_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcards',
            name='to',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
