# Generated by Django 4.1.4 on 2022-12-17 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0005_alter_giftcards_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcards',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
