# Generated by Django 4.1.4 on 2022-12-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0006_giftcards_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcards',
            name='price',
            field=models.FloatField(),
        ),
    ]
