# Generated by Django 4.1.4 on 2022-12-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0007_alter_giftcards_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcardtype',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
