# Generated by Django 4.1.4 on 2022-12-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0009_categories_giftcardtype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcardtype',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
