# Generated by Django 4.1.4 on 2022-12-21 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0010_giftcardtype_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcards',
            name='price',
        ),
    ]
